<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Empresa' . "\0" . 'id', '' . "\0" . 'Empresa' . "\0" . 'nombre', '' . "\0" . 'Empresa' . "\0" . 'cuit', '' . "\0" . 'Empresa' . "\0" . 'condIva', '' . "\0" . 'Empresa' . "\0" . 'mail', '' . "\0" . 'Empresa' . "\0" . 'domicilio', '' . "\0" . 'Empresa' . "\0" . 'codigoPostal', '' . "\0" . 'Empresa' . "\0" . 'fechaCreacion', '' . "\0" . 'Empresa' . "\0" . 'localidad', '' . "\0" . 'Empresa' . "\0" . 'provincia', '' . "\0" . 'Empresa' . "\0" . 'usuario', '' . "\0" . 'Empresa' . "\0" . 'password', '' . "\0" . 'Empresa' . "\0" . 'estado', '' . "\0" . 'Empresa' . "\0" . 'cuentas', '' . "\0" . 'Empresa' . "\0" . 'comisionACobrar', '' . "\0" . 'Empresa' . "\0" . 'mensualidades'];
        }

        return ['__isInitialized__', '' . "\0" . 'Empresa' . "\0" . 'id', '' . "\0" . 'Empresa' . "\0" . 'nombre', '' . "\0" . 'Empresa' . "\0" . 'cuit', '' . "\0" . 'Empresa' . "\0" . 'condIva', '' . "\0" . 'Empresa' . "\0" . 'mail', '' . "\0" . 'Empresa' . "\0" . 'domicilio', '' . "\0" . 'Empresa' . "\0" . 'codigoPostal', '' . "\0" . 'Empresa' . "\0" . 'fechaCreacion', '' . "\0" . 'Empresa' . "\0" . 'localidad', '' . "\0" . 'Empresa' . "\0" . 'provincia', '' . "\0" . 'Empresa' . "\0" . 'usuario', '' . "\0" . 'Empresa' . "\0" . 'password', '' . "\0" . 'Empresa' . "\0" . 'estado', '' . "\0" . 'Empresa' . "\0" . 'cuentas', '' . "\0" . 'Empresa' . "\0" . 'comisionACobrar', '' . "\0" . 'Empresa' . "\0" . 'mensualidades'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMensualidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensualidades', []);

        return parent::getMensualidades();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensualidades(array $mensualidades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensualidades', [$mensualidades]);

        return parent::setMensualidades($mensualidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuentas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuentas', []);

        return parent::getCuentas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuentas(array $cuentas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuentas', [$cuentas]);

        return parent::setCuentas($cuentas);
    }

    /**
     * {@inheritDoc}
     */
    public function getComisionACobrar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComisionACobrar', []);

        return parent::getComisionACobrar();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuentaDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuentaDefault', []);

        return parent::getCuentaDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function setComisionACobrar($comisionACobrar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComisionACobrar', [$comisionACobrar]);

        return parent::setComisionACobrar($comisionACobrar);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreProvincias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreProvincias', []);

        return parent::getNombreProvincias();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreEstados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreEstados', []);

        return parent::getNombreEstados();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuentaActiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuentaActiva', []);

        return parent::getCuentaActiva();
    }

    /**
     * {@inheritDoc}
     */
    public function getDatosArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatosArray', []);

        return parent::getDatosArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getCondIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondIva', []);

        return parent::getCondIva();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuit', []);

        return parent::getCuit();
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', []);

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', []);

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function setCuit($cuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuit', [$cuit]);

        return parent::setCuit($cuit);
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilio($domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilio', [$domicilio]);

        return parent::setDomicilio($domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal($codigoPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', [$codigoPostal]);

        return parent::setCodigoPostal($codigoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', [$fechaCreacion]);

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function setCondIva($condIva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondIva', [$condIva]);

        return parent::setCondIva($condIva);
    }

    /**
     * {@inheritDoc}
     */
    public function tieneProvincia(&$provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneProvincia', [$provincia]);

        return parent::tieneProvincia($provincia);
    }

}
