<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Guardavida extends \Guardavida implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'Guardavida' . "\0" . 'activo', '' . "\0" . 'Guardavida' . "\0" . 'created_at', '' . "\0" . 'Guardavida' . "\0" . 'modified_at', 'nombre', 'apellido', 'dni', 'domicilio', 'provincia', 'localidad', 'codpostal', 'telfijo', 'telcelular', 'foto', 'email', 'password', 'nosconocio', 'tipousuario', '' . "\0" . 'Guardavida' . "\0" . 'atributos', '' . "\0" . 'Guardavida' . "\0" . 'guarda_atributos'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'Guardavida' . "\0" . 'activo', '' . "\0" . 'Guardavida' . "\0" . 'created_at', '' . "\0" . 'Guardavida' . "\0" . 'modified_at', 'nombre', 'apellido', 'dni', 'domicilio', 'provincia', 'localidad', 'codpostal', 'telfijo', 'telcelular', 'foto', 'email', 'password', 'nosconocio', 'tipousuario', '' . "\0" . 'Guardavida' . "\0" . 'atributos', '' . "\0" . 'Guardavida' . "\0" . 'guarda_atributos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Guardavida $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getGuarda_atributos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuarda_atributos', []);

        return parent::getGuarda_atributos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuarda_atributos($guarda_atributos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuarda_atributos', [$guarda_atributos]);

        return parent::setGuarda_atributos($guarda_atributos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributos', []);

        return parent::getAtributos();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtributos($atributos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtributos', [$atributos]);

        return parent::setAtributos($atributos);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated_at($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated_at', [$created_at]);

        return parent::setCreated_at($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated_at()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated_at', []);

        return parent::getCreated_at();
    }

    /**
     * {@inheritDoc}
     */
    public function setModified_at($modified_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModified_at', [$modified_at]);

        return parent::setModified_at($modified_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getModified_at()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModified_at', []);

        return parent::getModified_at();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', []);

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni($dni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', [$dni]);

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilio($domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilio', [$domicilio]);

        return parent::setDomicilio($domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodpostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodpostal', []);

        return parent::getCodpostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodpostal($codpostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodpostal', [$codpostal]);

        return parent::setCodpostal($codpostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelfijo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelfijo', []);

        return parent::getTelfijo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelfijo($telfijo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelfijo', [$telfijo]);

        return parent::setTelfijo($telfijo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelcelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelcelular', []);

        return parent::getTelcelular();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelcelular($telcelular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelcelular', [$telcelular]);

        return parent::setTelcelular($telcelular);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', []);

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', [$foto]);

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getNosconocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNosconocio', []);

        return parent::getNosconocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNosconocio($nosconocio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNosconocio', [$nosconocio]);

        return parent::setNosconocio($nosconocio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipousuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipousuario', []);

        return parent::getTipousuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipousuario($tipousuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipousuario', [$tipousuario]);

        return parent::setTipousuario($tipousuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatosArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatosArray', []);

        return parent::getDatosArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcciones', []);

        return parent::getAcciones();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributoById($atr_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributoById', [$atr_id]);

        return parent::getAtributoById($atr_id);
    }

}
