<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mediodecodificado extends \Mediodecodificado implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'tipo', 'cant_registros', 'total', 'fecha', 'nombre_archivo', 'renglones', '' . "\0" . 'Mediodecodificado' . "\0" . 'decodificador'];
        }

        return ['__isInitialized__', 'id', 'tipo', 'cant_registros', 'total', 'fecha', 'nombre_archivo', 'renglones', '' . "\0" . 'Mediodecodificado' . "\0" . 'decodificador'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mediodecodificado $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDecodificador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecodificador', []);

        return parent::getDecodificador();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecodificador($decodificador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecodificador', [$decodificador]);

        return parent::setDecodificador($decodificador);
    }

    /**
     * {@inheritDoc}
     */
    public function getRenglones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRenglones', []);

        return parent::getRenglones();
    }

    /**
     * {@inheritDoc}
     */
    public function setRenglones($renglones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRenglones', [$renglones]);

        return parent::setRenglones($renglones);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($med_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$med_id]);

        return parent::setId($med_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCant_registros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCant_registros', []);

        return parent::getCant_registros();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalRegistrosArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalRegistrosArchivo', []);

        return parent::getTotalRegistrosArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCant_registros($cant_registros)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCant_registros', [$cant_registros]);

        return parent::setCant_registros($cant_registros);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre_archivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre_archivo', []);

        return parent::getNombre_archivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre_archivo($nombre_archivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre_archivo', [$nombre_archivo]);

        return parent::setNombre_archivo($nombre_archivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatosArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatosArray', []);

        return parent::getDatosArray();
    }

}
