<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Punto_interes extends \Punto_interes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'estado', 'updateip', 'altaip', 'usuarioAlta', 'alta_fecha', 'usuarioUpdate', 'update_fecha', 'linea', 'direccion', 'latlong', 'tipo', 'descripcionEs', 'descripcionEn', 'barrio'];
        }

        return ['__isInitialized__', 'id', 'estado', 'updateip', 'altaip', 'usuarioAlta', 'alta_fecha', 'usuarioUpdate', 'update_fecha', 'linea', 'direccion', 'latlong', 'tipo', 'descripcionEs', 'descripcionEn', 'barrio'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Punto_interes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDescripcionEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionEs', []);

        return parent::getDescripcionEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionEn', []);

        return parent::getDescripcionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionEs($descripcionEs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionEs', [$descripcionEs]);

        return parent::setDescripcionEs($descripcionEs);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionEn($descripcionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionEn', [$descripcionEn]);

        return parent::setDescripcionEn($descripcionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateip', []);

        return parent::getUpdateip();
    }

    /**
     * {@inheritDoc}
     */
    public function getAltaip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltaip', []);

        return parent::getAltaip();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioAlta', []);

        return parent::getUsuarioAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function getPropiedad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropiedad', []);

        return parent::getPropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlta_fecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlta_fecha', []);

        return parent::getAlta_fecha();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioUpdate', []);

        return parent::getUsuarioUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdate_fecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdate_fecha', []);

        return parent::getUpdate_fecha();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinea', []);

        return parent::getLinea();
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function getLatlong()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatlong', []);

        return parent::getLatlong();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getBarrio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarrio', []);

        return parent::getBarrio();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateip($updateip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateip', [$updateip]);

        return parent::setUpdateip($updateip);
    }

    /**
     * {@inheritDoc}
     */
    public function setAltaip($altaip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltaip', [$altaip]);

        return parent::setAltaip($altaip);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioAlta($usuarioAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioAlta', [$usuarioAlta]);

        return parent::setUsuarioAlta($usuarioAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropiedad($propiedad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropiedad', [$propiedad]);

        return parent::setPropiedad($propiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlta_fecha($alta_fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlta_fecha', [$alta_fecha]);

        return parent::setAlta_fecha($alta_fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioUpdate($usuarioUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioUpdate', [$usuarioUpdate]);

        return parent::setUsuarioUpdate($usuarioUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdate_fecha($update_fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdate_fecha', [$update_fecha]);

        return parent::setUpdate_fecha($update_fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function setLinea($linea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinea', [$linea]);

        return parent::setLinea($linea);
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function setLatlong($latlong)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatlong', [$latlong]);

        return parent::setLatlong($latlong);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setBarrio($barrio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarrio', [$barrio]);

        return parent::setBarrio($barrio);
    }

}
