<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Barrio extends \Barrio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'descripcion_es', 'descripcion_en', 'banner_es', 'banner_en', 'estado', 'detalle_es', 'detalle_en', 'banner_grande_es', 'banner_grande_en', 'mapa', 'texto_alt_es', 'texto_alt_en', 'meta_description_es', 'meta_description_en', 'texto_introductorio_en', 'texto_introductorio_es', 'guia_es', 'guia_en', 'guia_intro_es', 'guia_intro_en', 'guia_titular_es', 'guia_titular_en', 'path_google_maps', 'foto_portada'];
        }

        return ['__isInitialized__', 'id', 'descripcion_es', 'descripcion_en', 'banner_es', 'banner_en', 'estado', 'detalle_es', 'detalle_en', 'banner_grande_es', 'banner_grande_en', 'mapa', 'texto_alt_es', 'texto_alt_en', 'meta_description_es', 'meta_description_en', 'texto_introductorio_en', 'texto_introductorio_es', 'guia_es', 'guia_en', 'guia_intro_es', 'guia_intro_en', 'guia_titular_es', 'guia_titular_en', 'path_google_maps', 'foto_portada'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Barrio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionEs', []);

        return parent::getDescripcionEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionEn', []);

        return parent::getDescripcionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getBannerEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBannerEs', []);

        return parent::getBannerEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getBannerEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBannerEn', []);

        return parent::getBannerEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalleEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalleEs', []);

        return parent::getDetalleEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalleEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalleEn', []);

        return parent::getDetalleEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getBannerGrandeEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBannerGrandeEs', []);

        return parent::getBannerGrandeEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getBannerGrandeEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBannerGrandeEn', []);

        return parent::getBannerGrandeEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getMapa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMapa', []);

        return parent::getMapa();
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoAltEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoAltEs', []);

        return parent::getTextoAltEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoAltEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoAltEn', []);

        return parent::getTextoAltEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescriptionEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescriptionEs', []);

        return parent::getMetaDescriptionEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescriptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescriptionEn', []);

        return parent::getMetaDescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoIntroductorioEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoIntroductorioEn', []);

        return parent::getTextoIntroductorioEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoIntroductorioEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoIntroductorioEs', []);

        return parent::getTextoIntroductorioEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiaEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiaEs', []);

        return parent::getGuiaEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiaEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiaEn', []);

        return parent::getGuiaEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiaIntroEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiaIntroEs', []);

        return parent::getGuiaIntroEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiaIntroEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiaIntroEn', []);

        return parent::getGuiaIntroEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiaTitularEs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiaTitularEs', []);

        return parent::getGuiaTitularEs();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiaTitularEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiaTitularEn', []);

        return parent::getGuiaTitularEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getPathGoogleMaps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPathGoogleMaps', []);

        return parent::getPathGoogleMaps();
    }

    /**
     * {@inheritDoc}
     */
    public function getFotoPortada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotoPortada', []);

        return parent::getFotoPortada();
    }

}
